# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 585)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_app_label = QtWidgets.QLabel(Form)
        self.frame_app_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_app_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame_app_label.setObjectName("frame_app_label")
        self.verticalLayout.addWidget(self.frame_app_label)
        self.alg_radio = QtWidgets.QRadioButton(Form)
        self.alg_radio.setMaximumSize(QtCore.QSize(100, 16777215))
        self.alg_radio.setObjectName("alg_radio")
        self.verticalLayout.addWidget(self.alg_radio)
        self.task_radio = QtWidgets.QRadioButton(Form)
        self.task_radio.setMaximumSize(QtCore.QSize(100, 16777215))
        self.task_radio.setObjectName("task_radio")
        self.verticalLayout.addWidget(self.task_radio)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.name_label.setObjectName("name_label")
        self.verticalLayout_6.addWidget(self.name_label)
        self.name_line = QtWidgets.QLineEdit(Form)
        self.name_line.setMinimumSize(QtCore.QSize(100, 30))
        self.name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.name_line.setObjectName("name_line")
        self.verticalLayout_6.addWidget(self.name_line)
        self.add_alg_btn = QtWidgets.QPushButton(Form)
        self.add_alg_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.add_alg_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.add_alg_btn.setObjectName("add_alg_btn")
        self.verticalLayout_6.addWidget(self.add_alg_btn)
        self.del_alg_btn = QtWidgets.QPushButton(Form)
        self.del_alg_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.del_alg_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.del_alg_btn.setObjectName("del_alg_btn")
        self.verticalLayout_6.addWidget(self.del_alg_btn)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.get_all_btn = QtWidgets.QPushButton(Form)
        self.get_all_btn.setMinimumSize(QtCore.QSize(160, 40))
        self.get_all_btn.setObjectName("get_all_btn")
        self.verticalLayout_4.addWidget(self.get_all_btn)
        self.search_name_slot_label = QtWidgets.QLabel(Form)
        self.search_name_slot_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_name_slot_label.setObjectName("search_name_slot_label")
        self.verticalLayout_4.addWidget(self.search_name_slot_label)
        self.search_name_slot_line = QtWidgets.QLineEdit(Form)
        self.search_name_slot_line.setMinimumSize(QtCore.QSize(100, 30))
        self.search_name_slot_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_name_slot_line.setObjectName("search_name_slot_line")
        self.verticalLayout_4.addWidget(self.search_name_slot_line)
        self.search_name_btn = QtWidgets.QPushButton(Form)
        self.search_name_btn.setMinimumSize(QtCore.QSize(160, 40))
        self.search_name_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_name_btn.setObjectName("search_name_btn")
        self.verticalLayout_4.addWidget(self.search_name_btn)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.name_slot_label = QtWidgets.QLabel(Form)
        self.name_slot_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.name_slot_label.setObjectName("name_slot_label")
        self.verticalLayout_10.addWidget(self.name_slot_label)
        self.slot_name_line = QtWidgets.QLineEdit(Form)
        self.slot_name_line.setMinimumSize(QtCore.QSize(100, 30))
        self.slot_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slot_name_line.setObjectName("slot_name_line")
        self.verticalLayout_10.addWidget(self.slot_name_line)
        self.value_label = QtWidgets.QLabel(Form)
        self.value_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.value_label.setObjectName("value_label")
        self.verticalLayout_10.addWidget(self.value_label)
        self.slot_value_line = QtWidgets.QLineEdit(Form)
        self.slot_value_line.setMinimumSize(QtCore.QSize(100, 30))
        self.slot_value_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slot_value_line.setObjectName("slot_value_line")
        self.verticalLayout_10.addWidget(self.slot_value_line)
        self.search_slot_btn = QtWidgets.QPushButton(Form)
        self.search_slot_btn.setMinimumSize(QtCore.QSize(160, 40))
        self.search_slot_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_slot_btn.setObjectName("search_slot_btn")
        self.verticalLayout_10.addWidget(self.search_slot_btn)
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_label = QtWidgets.QLabel(Form)
        self.frame_label.setObjectName("frame_label")
        self.verticalLayout_2.addWidget(self.frame_label)
        self.frame_table = QtWidgets.QTreeWidget(Form)
        self.frame_table.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_table.setObjectName("frame_table")
        self.frame_table.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.frame_table)
        self.slot_label = QtWidgets.QLabel(Form)
        self.slot_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.slot_label.setObjectName("slot_label")
        self.verticalLayout_2.addWidget(self.slot_label)
        self.slot_table = QtWidgets.QTableWidget(Form)
        self.slot_table.setMinimumSize(QtCore.QSize(200, 0))
        self.slot_table.setMaximumSize(QtCore.QSize(16777215, 132))
        self.slot_table.setLineWidth(1)
        self.slot_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.slot_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.slot_table.setObjectName("slot_table")
        self.slot_table.setColumnCount(2)
        self.slot_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.slot_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_table.setHorizontalHeaderItem(1, item)
        self.slot_table.horizontalHeader().setVisible(False)
        self.slot_table.horizontalHeader().setCascadingSectionResizes(False)
        self.slot_table.horizontalHeader().setDefaultSectionSize(147)
        self.slot_table.horizontalHeader().setMinimumSectionSize(93)
        self.slot_table.verticalHeader().setVisible(False)
        self.slot_table.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.slot_table)
        self.set_slot_btn = QtWidgets.QPushButton(Form)
        self.set_slot_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.set_slot_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.set_slot_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.set_slot_btn.setObjectName("set_slot_btn")
        self.verticalLayout_2.addWidget(self.set_slot_btn)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.frame_app_label.setText(_translate("Form", "Фреймовая модель"))
        self.alg_radio.setText(_translate("Form", "Параметры"))
        self.task_radio.setText(_translate("Form", "Вакансия"))
        self.name_label.setText(_translate("Form", "Название:"))
        self.add_alg_btn.setText(_translate("Form", "Добавить"))
        self.del_alg_btn.setText(_translate("Form", "Удалить"))
        self.label_3.setText(_translate("Form", "Поиск"))
        self.get_all_btn.setText(_translate("Form", "Снова показать всё"))
        self.search_name_slot_label.setText(_translate("Form", "Название:"))
        self.search_name_btn.setText(_translate("Form", "Поиск по названию"))
        self.name_slot_label.setText(_translate("Form", "Слот:"))
        self.value_label.setText(_translate("Form", "Значение:"))
        self.search_slot_btn.setText(_translate("Form", "Поиск по значению"))
        self.label.setText(_translate("Form", "Управление"))
        self.frame_label.setText(_translate("Form", "Фреймами:"))
        self.frame_table.headerItem().setText(0, _translate("Form", "Вывод"))
        self.slot_label.setText(_translate("Form", "Слотами:"))
        item = self.slot_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Слот"))
        item = self.slot_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Значение"))
        self.set_slot_btn.setText(_translate("Form", "Применить"))

